@echo off
echo Starting PaySSD Application...
echo.
echo Starting Backend Server on Port 5000...
start "PaySSD Backend" cmd /k "cd /d "%~dp0" && npm run server"
echo.
echo Starting Frontend Client on Port 3000...
start "PaySSD Frontend" cmd /k "cd /d "%~dp0\client" && npm start"
echo.
echo Both servers are starting...
echo Backend: http://localhost:5000
echo Frontend: http://localhost:3000
echo.
echo Press any key to exit this window...
pause > nul