import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.0'

const url = Deno.env.get('SUPABASE_URL') || ''
const key = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') || ''
const client = createClient(url, key)

function corsHeaders() {
  return {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Content-Type': 'application/json'
  }
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders() })
  try {
    const body = await req.json()
    const email: string = (body?.email || '').toString().trim().toLowerCase()
    const password: string = (body?.password || '').toString()
    const business = body?.business || {}
    const accountType: 'business' | 'personal' = (business?.business_type === 'business') ? 'business' : 'personal'
    const contactName: string = (business?.contact_name || '').toString().trim()
    const contactPhone: string = (business?.contact_phone || '').toString().trim()

    if (!email || !password) {
      return new Response(JSON.stringify({ ok: false, error: 'missing_parameters' }), { status: 400, headers: corsHeaders() })
    }

    // Create user (or find existing)
    let userId: string | null = null
    const { data: created, error: createErr } = await client.auth.admin.createUser({ email, password, email_confirm: true })
    if (createErr) {
      // If user exists, fetch it
      const { data: list } = await client.auth.admin.listUsers()
      const found = list?.users?.find?.((u: any) => u?.email?.toLowerCase() === email)
      if (!found) {
        return new Response(JSON.stringify({ ok: false, error: 'create_user_failed', details: createErr.message }), { status: 400, headers: corsHeaders() })
      }
      userId = found.id
    } else {
      userId = created?.user?.id || null
    }

    if (!userId) {
      return new Response(JSON.stringify({ ok: false, error: 'no_user_id' }), { status: 400, headers: corsHeaders() })
    }

    // Split name
    const [firstName, ...rest] = contactName.split(' ')
    const lastName = rest.join(' ').trim()

    // Insert merchant profile (id generated by DB)
    const insertPayload: Record<string, any> = {
      user_id: userId,
      email,
      first_name: firstName || null,
      last_name: lastName || null,
      phone: contactPhone || null,
      account_type: accountType,
      documents: [],
    }

    if (accountType === 'business') {
      insertPayload.business_type = business?.business_type || null
      insertPayload.business_name = business?.business_name || null
      insertPayload.business_registration_number = business?.registration_number || null
      insertPayload.tax_id = business?.tax_id || null
      insertPayload.business_address = business?.business_address || null
    }

    const { data: merchantRow, error: mErr } = await client
      .from('merchants')
      .insert(insertPayload)
      .select('id, verification_status')
      .single()

    if (mErr) {
      return new Response(JSON.stringify({ ok: false, error: 'merchant_insert_failed', details: mErr.message }), { status: 400, headers: corsHeaders() })
    }

    // Ensure verification status is not blocking uploads (set to null if allowed)
    try {
      await client.from('merchants').update({ verification_status: null, verification_notes: null }).eq('id', merchantRow.id)
    } catch (_) {}

    // Try to generate sandbox API keys if RPC exists (best-effort)
    try {
      // Some deployments store keys in api_keys table via function
      await client.rpc('generate_api_keys', { p_merchant_id: merchantRow.id, p_key_type: 'sandbox' })
    } catch (_) {
      // Ignore if not present
    }

    return new Response(JSON.stringify({ ok: true, merchant_id: merchantRow.id }), { status: 200, headers: corsHeaders() })
  } catch (e) {
    return new Response(JSON.stringify({ ok: false, error: 'invalid_request', details: (e as Error)?.message }), { status: 400, headers: corsHeaders() })
  }
})

